config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    registrations: "users/registrations",
  }
  delete "destroy_user_session", to: "devise/sessions#destroy"
  devise_scope :user do
    get "user_show", to: "users/registrations#show"
    get "user_destroy", to: "users/sessions#index"
  end
  root 'posts#index'

  resources :posts do
    resources :images, only: [:new, :create]
    resources :comments, only: :create
    collection do
      get 'search'
    end
  end

end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :images, dependent: :destroy

  validates :name, presence: true, length: {maximum: 30}
  validates :introduction, presence: true, length: {maximum: 200}
  validates :images, presence: true
  validates_associated :images
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only:[:edit, :show]
  before_action :move_to_index, except: [:index, :show, :search]

  def index
    @posts = Post.includes(:user).order('created_at DESC')
  end

  def new
    @post = Post.new
    @post.images.new
  end

  def create
    Post.create(post_params)
  end

  def destroy
  end

  def edit
  end

  def updata
    post = Post.find(params[:id])
    post.updata(post_params)
  end

  def show
    @comment = Comment.new
    @comments = @post.comments.includes(:user)
  end

  def search
    @posts = Post.search(params[:keyword])
    respond_to do |format|
      format.html
      format.json
    end
  end

  private

  def post_params
    params.require(:post).permit(:name, :introduction, :image).merge(user_id: current_user.id)
  end

  def set_post
    @post = Post.find(params[:id])
  end

  def move_to_index
    redirect_to action: :index unless user_signed_in?
  end

end

app/views/posts/_edit.html.haml
= render 'header'
= render 'new'
= render 'footer'

app/views/posts/_footer.html.haml
.footer
  =link_to root_path do
    Mott

app/views/posts/_header.html.haml
.main_header
  .main_header_box
    .main_header_box_left
      =link_to root_path do
        Mott
    .main_header_box_center
      = form_with(url: search_posts_path, local: true, method: :get, class: "search-form") do |form|
        = form.text_field :keyword, placeholder: "投稿を検索する", class: "search-input"
        = form.submit "検索", class: "search-btn"
    .main_header_box_right
      - if user_signed_in?
        = link_to user_show_path(current_user) do
          = fa_icon 'user', class: 'head_left_icon'
        = link_to new_post_path do
          = fa_icon 'edit', class: 'head_right_icon'
      - else
        = link_to new_user_session_path do
          = fa_icon 'user', class: 'head_left_icon'
          = fa_icon 'edit', class: 'head_right_icon'

app/views/posts/_image_form.html.haml
= form_with model: @post, class: "image_form", local: true do |f|
  .image-box
    .image-box__name
      画像
      .image-box__name-require
        必須
    .image-box__fields
      #image-box
        - if @post.persisted?
          = f.fields_for :posts, :post do |i|
            .js-file_group{data: {index: i.index.to_s}}
              .preview-none
                .js-image-zone
                  - if item.persisted?
                    = image_tag @post.images[i.index].image.url, data: { index: i.index }, width: "50px", height: "50px"
                .js-edit 変更
                .js-remove 削除
              %label.input
                .input__box
                  .input__box__cam-icon
                    %i.fa.fa-camera.fa-lg
                  %p.input__box__p
                    ここをクリックしてアップロード
                = i.file_field :image, class: 'js-file', style: 'display:none'
            - if item.persisted?
              = i.check_box :_destroy, data:{ index: i.index }, class: "hidden-destroy"
        - else
          = f.fields_for :images, @post do |i|
            .js-file_group{data: {index: i.index.to_s}}
              .preview-none
                .js-image-zone
                  - if @post.persisted?
                    = image_tag post.images[i.index].image.url, data: { index: i.index }, width: "138px", height: "82px"
                .js-edit 変更
                .js-remove 削除
              %label.input
                .input__box
                  .input__box__cam-icon
                    %i.fa.fa-camera.fa-lg
                  %p.input__box__p
                    ここをクリックしてアップロード
                = i.file_field :image, class: 'js-file', style: 'display:none'
        - if @post.persisted?
          .js-file_group{data: {index: item.images.count}}
            .preview-none
              .js-image-zone
              .js-edit 変更
              .js-remove 削除
            %label.input
              = file_field_tag :image, name: "item[images_attributes][#{item.images.count}][image]", class: 'js-file', style: "display:none"
              .input__box
                .input__box__cam-icon
                  %i.fa.fa-camera.fa-lg
                %p.input__box__p
                  ここをクリックしてアップロード
      #how-many-image

app/views/posts/index.html.haml
= render "header"
.main_contents
  -# - @post.each do |post|
  = image_tag "uyunienko.jpg"
  .main_contents_data
    .main_contents_data_name
      Nickname: cris
    .main_contents_data_place
      Place: ウユニ塩湖
  .main_contents_text
    とても綺麗だった。また行きたい！！！
= render "footer"

app/views/posts/new.html.haml
= form_with(url: new_post_path, local: true, method: :get) do |f|
  = render "header"
  .new_posts
    .new_posts_title
      新規投稿
    .new_posts_data
      .new_posts_data_image
        .new_posts_data_image_icon
          .fa.fa-camera
          = f.file_field :images, class: 'post_image'
      .new_posts_data_text
        = f.text_area :introduction, autofocus: true, placeholder: '旅の想い出'
        .new_posts_data_text_place
          = f.text_area :name, autofocus: true, placeholder: '行き先'
    .new_posts_btn
      = f.submit "投稿する"
= render "footer"